# Generated by Django 6.0.3 on 2026-03-15 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='projects/')),
                ('tags', models.CharField(help_text='Tecnologías separadas por coma. Ej: Reac, Python, PostgreSQL', max_length=500)),
                ('demo_url', models.URLField(blank=True, null=True, verbose_name='Demo URL')),
                ('code_url', models.URLField(blank=True, null=True, verbose_name='Código fuente URL')),
                ('is_featured', models.BooleanField(default=True, verbose_name='Destacado')),
                ('order', models.PositiveIntegerField(default=0, help_text='Orden de aparición (Menor primero)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Project',
                'verbose_name_plural': 'Projects',
                'ordering': ['order', '-created_at'],
            },
        ),
    ]
