# Generated by Django 6.0.3 on 2026-03-21 02:08

import markdownx.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_alter_category_name_alter_post_content_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='name_en',
            field=models.CharField(max_length=100, null=True, verbose_name='Nombre'),
        ),
        migrations.AddField(
            model_name='category',
            name='name_es_mx',
            field=models.CharField(max_length=100, null=True, verbose_name='Nombre'),
        ),
        migrations.AddField(
            model_name='post',
            name='content_en',
            field=markdownx.models.MarkdownxField(null=True, verbose_name='Contenido'),
        ),
        migrations.AddField(
            model_name='post',
            name='content_es_mx',
            field=markdownx.models.MarkdownxField(null=True, verbose_name='Contenido'),
        ),
        migrations.AddField(
            model_name='post',
            name='title_en',
            field=models.CharField(max_length=200, null=True, unique=True, verbose_name='Título'),
        ),
        migrations.AddField(
            model_name='post',
            name='title_es_mx',
            field=models.CharField(max_length=200, null=True, unique=True, verbose_name='Título'),
        ),
    ]
