# Generated by Django 6.0.3 on 2026-03-21 02:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_category_name_en_category_name_es_mx_post_content_en_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='short_description',
            field=models.CharField(blank=True, help_text='Breve resumen que aparecerá en la tarjeta de la lista de artículos.', max_length=255, null=True, verbose_name='Descripción corta'),
        ),
    ]
