# Generated by Django 6.0.3 on 2026-03-21 02:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_post_short_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='short_description_en',
            field=models.CharField(blank=True, help_text='Breve resumen que aparecerá en la tarjeta de la lista de artículos.', max_length=255, null=True, verbose_name='Descripción corta'),
        ),
        migrations.AddField(
            model_name='post',
            name='short_description_es_mx',
            field=models.CharField(blank=True, help_text='Breve resumen que aparecerá en la tarjeta de la lista de artículos.', max_length=255, null=True, verbose_name='Descripción corta'),
        ),
    ]
