# Generated by Django 6.0.3 on 2026-03-21 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_post_short_description_en_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='slug_en',
            field=models.SlugField(max_length=200, null=True, unique=True, verbose_name='Slug'),
        ),
        migrations.AddField(
            model_name='post',
            name='slug_es_mx',
            field=models.SlugField(max_length=200, null=True, unique=True, verbose_name='Slug'),
        ),
    ]
